name: ocookie
description: Cookie and Set-Cookie parser and serializer.
repository: https://github.com/odroe/ocookie
funding:
  - https://github.com/sponsors/medz
  - https://opencollective.com/openodroe
topics:
  - cookie
  - parser
  - serializer

version: 0.1.0
environment:
  sdk: ^3.6.0

dependencies:
  http_parser: ^4.1.1

dev_dependencies:
  lints: 6.1.0
  test: ^1.24.0
